
#CreateGlobalPalette : menu_palette
#PNGImages           :
 GDfont
 menu
 sides
 header
 INSANE
 EASY_DEMON
 HARD_DEMON

#GroupASM            : tete
#Palette             : menu_palette
#OutputPaletteImage  :
#PNGImages           :
 INSANE

#GroupASM            : tete
#Palette             : menu_palette
#OutputPaletteImage  :
#PNGImages           :
 EASY_DEMON

#GroupASM            : tete
#Palette             : menu_palette
#OutputPaletteImage  :
#PNGImages           :
 HARD_DEMON

#GroupASM            : menu
#Palette             : menu_palette
#Tilemap             : 30,48,true
#NoPaletteArray      :
#PNGImages           :
 menu

#GroupASM            : sides
#Palette             : menu_palette
#NoPaletteArray      :
#PNGImages           :
 sides

#GroupASM            : header
#Palette             : menu_palette
#NoPaletteArray      :
#PNGImages           :
 header

#GroupASM            : GDfont
#Palette             : menu_palette
#Tilemap             : 28,28,true
#NoPaletteArray      :
#PNGImages           :
 GDfont


