
#CreateGlobalPalette : game_palette
#PNGImages           :
 GD
 jump

#GroupASM            : tiles
#Palette             : game_palette
#Tilemap             : 21,21,true
#OutputPaletteImage  :
#PNGImages           :
 GD

#GroupASM            : jump
#Palette             : game_palette
#Tilemap             : 30,30,true
#NoPaletteArray      :
#PNGImages           :
 jump
