; This file is used to compress the pixel shadow, menu, and tiles data using a simple RLE compression algorithm.
; The compressed data is stored in an appvar for use in the game.
; Run the program on your calculator, it will create the appvar either :
; 		- "GDGrphc" containing the compressed graphics data
; 	or 	- "GDMenu" containing the compressed menu data
; ...according to the selected compression option (see the comments in the code).
; NB: All *.asm files have been generated using convimg (https://github.com/mateoconlechuga/convimg)

.nolist
	#include "ti84pce.inc"
	#define db .db
	#define dw .dw
	#define dl .dl
	#macro bcall(x)
		call x
	#endmacro
	#DEFINE BGCl	$7F
.list
	.org userMem-2
	.db tExtTok,tAsm84CeCmp

	ld de,pixelshadow+3
	ld hl,tiles  ; Change to menu to compress the menu instead of the tiles
	ld ix,0
startingCompression:
	ld c,(hl)
	ld b,0
countPxls:
	inc hl
	inc b
	ld a,b
	or a
	jr z,endCount
	ld a,(hl)
	cp c
	jr z,countPxls
endCount:
	ex de,hl
	ld (hl),b
	inc hl
	ld (hl),c
	inc hl
	ex de,hl
	inc ix
	ld a,(hl)
	cp -1
	jr nz,startingCompression
	ld (pixelshadow),ix

	ld hl,AppVarName
	call _mov9toop1
	call _chkfindsym
	call nc,_DELVAR
	ld hl,(pixelshadow)
	add hl,hl
	inc hl
	inc hl
	inc hl
	push hl
	call _createAppVar
	inc de
	inc de
	ld hl,pixelshadow
	pop bc
	ldir
	ret

AppVarName:
	.db appvarObj,"GDGrphc",0
AppVarName2:
	.db appvarObj,"GDMenu",0


; ********************************************************************
; Uncomment either of these sections to compress the menu or the tiles
; ! Do not uncomment both !
; ********************************************************************

menu:
;#include "spritesGD/GDFont.asm"
;#include "spritesGD/menu.asm"
;#include "spritesGD/sides.asm"
;#include "spritesGD/header.asm"
	.db -1
.echo $-menu

tiles:
#include "spritesGD/tiles.asm"
#include "spritesGD/jump.asm"
#include "spritesGD/spaceship.asm"
	.db -1
.echo $-tiles

.end
